name: Deploy Cloud Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Check authorized user
        run: gcloud auth list
          
      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy enrich_issue \
            --gen2 \
            --runtime=python310 \
            --region=${{ secrets.GCP_REGION }} \
            --trigger-topic=defect-detected \
            --entry-point=enrich_issue